GET http://localhost:3000/users

###
GET http://localhost:3000/users/12

###
POST http://localhost:3000/users/5
Content-Type: application/json

{
    "email": "student3@habibuniversity.edu",
    "password": "hashed_password_5", // Use a hashed password
    "role": "student",
    "name": "John Doe",
    "department": "Mathematics",
    "position": "Student"
}